package com.epam.util;

public class ControllerConstants {

    public static final String CURRENT_PAGE = "currentPage",
            PAGE = "page",
            COMMAND = "command",
            ID = "id",
            BOOK_ID = "bookId",
            LOGIN = "login",
            PASSWORD = "password",
            SECOND_PASSWORD = "secondPassword",
            ROLE = "role",
            LAST_COMMAND = "lastCommand",
            ADDRESS = "address",
            MESSAGE = "message",
            LOCAL = "local",
            USER = "user",
            REQUEST_ENCODING = "requestEncoding",
            UTF8 = "UTF-8",
            CONTENT_TYPE = "text/html; charset=UTF-8",
            FRONT_CONTROLLER = "frontController?",
            BOOK = "book",
            TITLE = "title",
            AUTHOR = "author",
            PUBLISHER = "publisher",
            GENRE = "genre",
            DESCRIPTION = "description",
            IS_HARD_COVER = "isHardCover",
            NUMBER_OF_PAGES = "numberOfPages",
            PUBLISHING_YEAR = "publishingYear",
            RESERVED_BOOKS = "reservedBooks",
            DEFAULT_PAGE_NUMBER = "1",
            PAGEABLE = "pageable",
            CURRENT_PAGE_RESERVE = "currentPageReserve",
            PAGEABLE_RESERVES = "pageableReserves",
            CURRENT_PAGE_USER = "currentPageUser",
            PAGEABLE_USERS = "pageableUsers",
            PAGEABLE_ORDERS = "pageableOrders";

}
